# file: C:\Users\ADITI\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\_pytest\pathlib.py
# hypothesis_version: 6.135.14

[420, 448, 1921, '.', '.lock', '.pyc', '.pyo', '1', '\\\\', '\\\\?\\', '\\\\?\\UNC\\', '_', '_AnyPurePath', '__init__', '__init__.py', 'append', 'current', 'errno', 'garbage-*', 'importlib', 'prepend', 'win', 'win32', 'winerror']